excludes:
  paths:
    - pattern: "benchmarks/**"
      reason: "TEST_OF"
      comment: Licenses contained in this directory are used for benchmarks and do not apply to the OSS Review Toolkit.
    - pattern: "tests/**"
      reason: "TEST_OF"
      comment: Licenses contained in this directory are used for testing and do not apply to the OSS Review Toolkit.
    - pattern: "valkey-glide/**"
      reason: "BUILD_TOOL_OF"
      comment: Excluding submodule with GLIDE core repo to avoid it being analysed twice
  scopes:
    - pattern: "xunit.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: Packages for testing only. Not part of released artifacts.
